### ISSUE TITLE
[Proposal] 브랜치 전략 기획

### ISSUE THREAD

**Issue by Lcheck** [threelee/DataStructure-Master#2]
## 기획 및 설계 제안 내용
master를 메인으로 두고,  development 브랜치로 분기해 작업하는 게 좋을 것 같습니다.
참고 자료를 기준으로 분기/통합 시점을 잡으면 될 것 같습니다.

## 참고 자료
https://wayhome25.github.io/assets/post-img/cs/data-structure.png

**Comment by sohenney** [comment]
단순/선형/비선형 구조에서 3가지 브랜치로 다시 나누는게 좋을 것 같습니다!

**Comment by lys4321** [comment]
저도 그게 좋을것 같습니다.

**Comment by sohenney** [comment]
생각해보니 마스터 브랜치 1개에 단순.선형.비선형 브랜치 3개로 나누어 그 브랜치에서 또 저희 각각의 브랜치(유섭,은호,소현)로 나누는 건 어떤가요?
총 마스터 1개, 큰 브랜치 3개, 작은 브랜치 9개입니다!
