### ISSUE TITLE
[Proposal] README.md 파일 구성 기획

### ISSUE THREAD

**Issue by lys4321** [threelee/DataStructure-Master#4]
저희 README.md 파일 내용 구성을 
1. 목적
2. 용도
3. 이용방법
4. 출처
이렇게 하는건 다들 어떠신가요?

**Comment by sohenney** [comment]
좋아요! 파트 나눠서 하는 게 좋을 것 같은데 어떠신가요??

**Comment by Lcheck** [comment]
네넵. 그럼 목적/용도/이용방법 세가지로 나눠서 각자 원고 작성후 취합하면 될 것 같습니다. 출처는 자료 모아지면 입력하죠!
